
variables:
  GIT_STRATEGY: fetch

cache:
    paths:
    - .cache/
    
AMMR1.6_Tests:
  stage: test
  script:
    - pytest --ff Tests 
  tags:
    - ams
    - python    
    
AMMR2.0_Tests:
  stage: test

  script:
    - git clone -q --depth 1 git@gitlab.com:AMMR-beta/ammr-beta.git -b ammr_beta
    - pytest --ff --ammr=ammr-beta Tests
  tags:
    - ams
    - python    
